const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {StoryRuntime}=require('../work/core/story/StoryRuntime.js');
const {createInitialState}=require('../work/core/core/GameState.js');
const {LocalSave}=require('../work/core/save/LocalSave.js');
const manifest=JSON.parse(fs.readFileSync('assets/resources/data/story/chapter04/chapter04_manifest.json'));
const episodes=manifest.episodes.map(e=>JSON.parse(fs.readFileSync('assets/resources/'+e.resource+'.json')));
function storage(){const data=new Map();return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)}}
function walk(s,choice){const local=new LocalSave(storage(),'test'),visited=[];for(const ep of episodes){let r=new StoryRuntime(s,x=>local.save(x));r.load(ep,'CH04');let n=r.current();while(n.type!=='episodeEnd'){visited.push(n.id);const loaded=local.load();assert.deepEqual(loaded.progress,s.progress);assert.deepEqual(loaded.flags,s.flags);assert.deepEqual(loaded.stats,s.stats);assert.deepEqual(loaded.life,s.life);r=new StoryRuntime(loaded,x=>local.save(x));r.load(ep,'CH04');assert.equal(r.current().id,n.id);s=loaded;n=n.type==='choice'?r.choose(choice,n.id):['passage','phone'].includes(n.type)?r.advance(n.id):r.complete(n.id)}}return{s,visited}}
test('eight chapter 04 combinations preserve family and planning consequences through every-node save reload',()=>{
 for(const family of [false,true])for(const discuss of [false,true])for(const ask of [false,true]){
  const state=createInitialState();state.flags[family?'CH02_TOLD_FAMILY_RELATION':'CH02_HID_FAMILY_RELATION']=true;state.flags[discuss?'CH03_DISCUSS_PLANS':'CH03_ASSUMED_SAME_CITY']=true;state.life.memoryRecords.GRADUATION={title:'毕业那年',status:'fragmentary',evidence:['2009.6 南门照片']};state.flags.TOLD_PARTNER_XIA=true;
  const {s,visited}=walk(state,ask?'ASK':'PROMISE');
  for(const [yes,no,condition] of [['CH04_EP01_ASK','CH04_EP01_SET',discuss],['CH04_EP02_COMPARE','CH04_EP02_REARRANGE',discuss],['CH04_EP03_KNOWN','CH04_EP03_LATE',family],['CH04_EP05_AGREED','CH04_EP05_CORRECTED',ask],['CH04_EP06_LISTEN','CH04_EP06_FIX',discuss],['CH04_EP06_ASK_AGAIN','CH04_EP06_PROMISE_AGAIN',ask]]){assert.ok(visited.includes(condition?yes:no));assert.ok(!visited.includes(condition?no:yes));}
  assert.ok(s.flags[ask?'CH04_ASKED_SUMMER_PLAN':'CH04_PROMISED_FOR_XIA']);assert.ok(!s.flags[ask?'CH04_PROMISED_FOR_XIA':'CH04_ASKED_SUMMER_PLAN']);assert.ok(s.flags.CH04_READ_TIMETABLES&&s.flags.CH04_SEEN_STREET_PHOTO);assert.ok(s.flags.TOLD_PARTNER_XIA);assert.equal(s.life.time.year,2011);assert.equal(s.life.time.month,6);assert.equal(s.life.stage,'student');assert.equal(s.life.relationships.XIA,'异地来往');assert.equal(s.life.memoryRecords.DISTANCE.status,'fragmentary');assert.deepEqual(s.life.memoryRecords.GRADUATION.evidence,['2009.6 南门照片']);assert.deepEqual(s.endings,{});assert.ok(!s.flags.READ_FULL_LETTER&&!s.flags.UNDERSTOOD_BREAKUP_TRUTH&&!s.flags.FOUND_FULL_RECORDING);
 }
});
test('chapter 04 ordinary missed calls do not become choices or unlock endings, and its decision only has small effects',()=>{
 const nodes=episodes.flatMap(e=>e.nodes),choices=nodes.filter(n=>n.type==='choice');assert.equal(choices.length,1);assert.equal(choices[0].id,'CH04_EP04_CHOICE');for(const option of choices[0].options)for(const delta of Object.values(option.effects))assert.ok(Math.abs(delta)<=2);
 for(const ep of episodes)for(const n of ep.nodes){if(n.lifeContext?.time)assert.ok(n.lifeContext.time.year>=2009&&n.lifeContext.time.year<=2011);assert.ok(!n.setFlags?.some(f=>['READ_FULL_LETTER','FOUND_FULL_RECORDING','UNDERSTOOD_BREAKUP_TRUTH'].includes(f)));}
 const local=new LocalSave(storage(),'test'),s=createInitialState();s.progress={chapterId:'CH04',episodeId:'CH04_EP05',nodeId:'CH04_EP05_PHOTO',readingOffset:0};const r=new StoryRuntime(s,x=>local.save(x));r.load(episodes[4],'CH04');r.complete('CH04_EP05_PHOTO');const first=structuredClone(s);s.progress.nodeId='CH04_EP05_PHOTO';r.complete('CH04_EP05_PHOTO');assert.deepEqual(s.stats,first.stats);assert.deepEqual(s.life.memoryRecords,first.life.memoryRecords);assert.deepEqual(s.readNodeIds,first.readNodeIds);
});
test('old chapter 03 boundary save enters chapter 04 and keeps prior cursor data and evidence if loading fails',()=>{
 const s=createInitialState(),local=new LocalSave(storage(),'test');s.progress={chapterId:'CH03',episodeId:'CH03_EP06',nodeId:'CH03_EP06_END',readingOffset:0};s.flags.CH03_ASSUMED_SAME_CITY=true;s.flags.CH02_HID_FAMILY_RELATION=true;s.stats.honesty=9;s.life.memoryRecords.GRADUATION={title:'毕业那年',status:'fragmentary',evidence:['未来信封']};local.save(s);
 const restored=local.load(),r=new StoryRuntime(restored,x=>local.save(x)),before=structuredClone(restored);assert.throws(()=>r.load({...episodes[0],startNode:'MISSING'},'CH04'),/Missing start/);assert.deepEqual(local.load().progress,before.progress);assert.deepEqual(restored,before);r.load(episodes[0],'CH04');assert.equal(r.current().id,'CH04_EP01_N001');assert.equal(restored.stats.honesty,9);assert.ok(restored.flags.CH03_ASSUMED_SAME_CITY);assert.deepEqual(restored.life.memoryRecords.GRADUATION.evidence,['未来信封']);assert.equal(local.load().progress.chapterId,'CH04');
});
