const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {StoryRuntime}=require('../work/core/story/StoryRuntime.js'),{createInitialState}=require('../work/core/core/GameState.js'),{LocalSave}=require('../work/core/save/LocalSave.js');
const manifest=JSON.parse(fs.readFileSync('assets/resources/data/story/chapter06/chapter06_manifest.json'));
const episodes=manifest.episodes.map(e=>JSON.parse(fs.readFileSync('assets/resources/'+e.resource+'.json')));
function storage(){const data=new Map();return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)}}
function walk(s){const local=new LocalSave(storage(),'test'),visited=[];let month=6;for(const ep of episodes){let r=new StoryRuntime(s,x=>local.save(x));r.load(ep,'CH06');let n=r.current();while(n.type!=='episodeEnd'){visited.push(n.id);assert.ok(s.life.time.month>=month);month=s.life.time.month;assert.equal(s.life.time.year,2013);assert.equal(s.life.stage,n.id==='CH06_EP01_N001'?'graduate':'working');if(!visited.includes('CH06_EP05_NOTE'))assert.ok(!s.flags.CH06_PARTED_2013);const restored=local.load();assert.deepEqual(restored.progress,s.progress);assert.deepEqual(restored.flags,s.flags);assert.deepEqual(restored.stats,s.stats);assert.deepEqual(restored.readNodeIds,s.readNodeIds);assert.deepEqual(restored.life,s.life);s=restored;r=new StoryRuntime(s,x=>local.save(x));r.load(ep,'CH06');assert.equal(r.current().id,n.id);n=['passage','phone'].includes(n.type)?r.advance(n.id):r.complete(n.id);}}return{s,visited}}
const branches=[['CH06_EP01_SHARE','CH06_EP01_CORRECT','share'],['CH06_EP02_EARLY','CH06_EP02_LATE','family'],['CH06_EP03_ASKED','CH06_EP03_REVISED','ask'],['CH06_EP03_LISTEN','CH06_EP03_RECONSIDER','discuss'],['CH06_EP04_SEPARATE','CH06_EP04_CORRECTED','share']];
test('all sixteen chapter 06 histories keep concrete earlier consequences, stats and every-node saves',()=>{
 for(const family of [false,true])for(const discuss of [false,true])for(const ask of [false,true])for(const share of [false,true]){const initial=createInitialState();initial.flags[family?'CH02_TOLD_FAMILY_RELATION':'CH02_HID_FAMILY_RELATION']=true;initial.flags[discuss?'CH03_DISCUSS_PLANS':'CH03_ASSUMED_SAME_CITY']=true;initial.flags[ask?'CH04_ASKED_SUMMER_PLAN':'CH04_PROMISED_FOR_XIA']=true;initial.flags[share?'CH05_TALKED_JOB_CONDITIONS':'CH05_ASSUMED_RETURN_FOR_JOB']=true;initial.flags.TOLD_PARTNER_XIA=true;initial.stats.honesty=9;initial.life.memoryRecords.WORK_PLANS={title:'毕业以前的打算',status:'fragmentary',evidence:['2013.6各自的报到备忘']};const before=structuredClone(initial),{s,visited}=walk(initial),values={family,discuss,ask,share};
  for(const [yes,no,key]of branches){assert.ok(visited.includes(values[key]?yes:no));assert.ok(!visited.includes(values[key]?no:yes));}
  assert.deepEqual(s.stats,before.stats);for(const [flag,value]of Object.entries(before.flags))assert.equal(s.flags[flag],value);assert.deepEqual(s.life.memoryRecords.WORK_PLANS,before.life.memoryRecords.WORK_PLANS);assert.equal(s.life.time.month,12);assert.equal(s.life.relationships.XIA,'已经分开');assert.equal(s.life.memoryRecords.WORK_START.status,'fragmentary');assert.equal(s.life.memoryRecords.BREAKUP.status,'fragmentary');assert.ok(s.flags.CH06_READ_WORK_NOTE&&s.flags.CH06_READ_VISIT_DATES&&s.flags.CH06_READ_STATION_NOTE&&s.flags.CH06_PARTED_2013);assert.deepEqual(s.endings,{});assert.ok(!s.flags.READ_FULL_LETTER&&!s.flags.FOUND_FULL_RECORDING&&!s.flags.UNDERSTOOD_BREAKUP_TRUTH);assert.equal(visited.length,30);
 }
});
test('the parting is reached after years of context, without a new choice or premature full-truth gate',()=>{
 const nodes=episodes.flatMap(e=>e.nodes);assert.equal(nodes.filter(n=>n.type==='choice').length,0);assert.ok(nodes.every(n=>!n.effects));for(const n of nodes){assert.ok(!n.setFlags?.some(f=>['READ_FULL_LETTER','FOUND_FULL_RECORDING','UNDERSTOOD_BREAKUP_TRUTH'].includes(f)));if(n.lifeContext?.memory)assert.equal(n.lifeContext.memory.status,'fragmentary');}
 const e=episodes[4],s=createInitialState(),r=new StoryRuntime(s,()=>{});r.load(e,'CH06');assert.ok(!s.flags.CH06_PARTED_2013);r.advance('CH06_EP05_N001');assert.ok(!s.flags.CH06_PARTED_2013);r.advance('CH06_EP05_TALK');assert.equal(s.life.relationships.XIA,'已经分开');assert.ok(!s.flags.CH06_PARTED_2013);r.advance('CH06_EP05_PLATFORM');r.complete('CH06_EP05_NOTE');assert.ok(s.flags.CH06_PARTED_2013);const first=structuredClone(s);s.progress.nodeId='CH06_EP05_NOTE';r.complete('CH06_EP05_NOTE');assert.deepEqual(s.stats,first.stats);assert.deepEqual(s.life.memoryRecords,first.life.memoryRecords);assert.deepEqual(s.readNodeIds,first.readNodeIds);
});
test('old chapter 05 boundary keeps cursor and evidence on failure then resumes at the June visit',()=>{
 const s=createInitialState(),local=new LocalSave(storage(),'test');s.progress={chapterId:'CH05',episodeId:'CH05_EP06',nodeId:'CH05_EP06_END',readingOffset:0};s.flags.CH05_ASSUMED_RETURN_FOR_JOB=true;s.life.memoryRecords.WORK_PLANS={title:'毕业以前的打算',status:'fragmentary',evidence:['2013.6各自的报到备忘']};local.save(s);const restored=local.load(),r=new StoryRuntime(restored,x=>local.save(x)),before=structuredClone(restored);assert.throws(()=>r.load({...episodes[0],startNode:'MISSING'},'CH06'),/Missing start/);assert.deepEqual(restored,before);assert.deepEqual(local.load().progress,before.progress);r.load(episodes[0],'CH06');assert.equal(r.current().id,'CH06_EP01_N001');assert.equal(restored.life.stage,'graduate');assert.equal(restored.life.time.month,6);assert.ok(restored.flags.CH05_ASSUMED_RETURN_FOR_JOB);assert.deepEqual(restored.life.memoryRecords.WORK_PLANS.evidence,['2013.6各自的报到备忘']);
});
test('missing earlier decisions use common passages and never invent any of the four histories',()=>{
 const {s,visited}=walk(createInitialState());for(const [yes,no]of branches){assert.ok(!visited.includes(yes)&&!visited.includes(no));}assert.equal(visited.length,25);for(const f of ['CH02_TOLD_FAMILY_RELATION','CH02_HID_FAMILY_RELATION','CH03_DISCUSS_PLANS','CH03_ASSUMED_SAME_CITY','CH04_ASKED_SUMMER_PLAN','CH04_PROMISED_FOR_XIA','CH05_TALKED_JOB_CONDITIONS','CH05_ASSUMED_RETURN_FOR_JOB'])assert.ok(!s.flags[f]);assert.ok(s.flags.CH06_PARTED_2013);assert.equal(s.life.time.month,12);
});
