const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const [url,seedFile,outDir]=process.argv.slice(2);if(!outDir)throw Error('Usage: URL genuine-ch08-none-report output-directory');
const expectedAudio=JSON.parse(fs.readFileSync('art/original/audio/manifest.json'));const seed=JSON.parse(fs.readFileSync(seedFile)).endState;assert.ok(!seed.flags.FOUND_FULL_RECORDING);assert.equal(seed.progress.chapterId,'CH08');
// Browser fixture returns a genuine no-recording save to the still-unread audio
// source. Only the initial cursor changes; the running game's state is untouched.
seed.progress={chapterId:'CH08',episodeId:'CH08_EP03',nodeId:'CH08_EP03_AUDIO',readingOffset:0};
let browser;(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:540,height:960},hasTouch:true,isMobile:true});const page=await context.newPage(),errors=[],failedRequests=[];fs.mkdirSync(outDir,{recursive:true});
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))failedRequests.push(r.url())});
await page.addInitScript(raw=>{if(!sessionStorage.getItem('audio.seeded')){localStorage.setItem('yushengweiji.save.v1',raw);sessionStorage.setItem('audio.seeded','1')}},JSON.stringify(seed));
const snap=()=>page.evaluate(()=>{const cc=window.cc,s=cc?.director.getScene(),buttons=[],labels=[],audio=[];let state;function walk(n){if(!n.activeInHierarchy)return;const m=n.getComponent('StoryManager');if(m?.hasState())state=m.state;const l=n.getComponent(cc.Label);if(l)labels.push(l.string);const b=n.getComponent(cc.Button);if(b)buttons.push({title:n.children.find(c=>c.getComponent(cc.Label))?.getComponent(cc.Label)?.string,enabled:b.interactable,x:270+n.worldPosition.x/2,y:480-n.worldPosition.y/2});for(const a of [n.getComponent('StoryView')?.audio?.source].filter(Boolean))audio.push({playing:a.playing,time:a.currentTime,duration:a.clip?.getDuration(),valid:a.isValid});for(const c of n.children)walk(c)}if(s)walk(s);return{state,buttons,labels,audio,save:localStorage.getItem('yushengweiji.save.v1')}});
const tap=async title=>{for(let i=0;i<100;i++){const b=(await snap()).buttons.find(b=>b.title===title&&b.enabled);if(b){await page.touchscreen.tap(b.x,b.y);await page.waitForTimeout(350);return}await page.waitForTimeout(100)}throw Error('No ready button '+title)};
await page.goto(url);await tap('继续');await tap('播放');await page.waitForTimeout(1800);let s=await snap();fs.writeFileSync(path.join(outDir,'play-start.json'),JSON.stringify(s,null,2));assert.ok(s.audio.some(a=>a.playing&&a.time>1&&Math.abs(a.duration-expectedAudio.duration)<.2&&a.duration>expectedAudio.previewDuration+15));assert.ok(!s.state.flags.FOUND_FULL_RECORDING);assert.ok(!s.buttons.find(b=>b.title==='继续').enabled);const playing=s.audio[0];await page.screenshot({path:path.join(outDir,'playing.png')});
await tap('暂停 / 继续播放');const paused=(await snap()).audio[0];await page.waitForTimeout(1200);const still=(await snap()).audio[0];assert.equal(still.playing,false);assert.ok(Math.abs(still.time-paused.time)<.15);await tap('暂停 / 继续播放');await page.waitForTimeout(1100);assert.ok((await snap()).audio[0].time>paused.time+.5);
// Wait in short intervals for the real media ENDED event, never seeking or
// setting offsets directly to award the full recording evidence.
for(let i=0;i<Math.ceil(expectedAudio.duration)+20;i++){s=await snap();if(s.buttons.find(b=>b.title==='继续').enabled)break;await page.waitForTimeout(1000)}
s=await snap();assert.ok(s.buttons.find(b=>b.title==='继续').enabled);assert.ok(s.state.progress.readingOffset>=.99);assert.ok(!s.state.flags.FOUND_FULL_RECORDING);await page.waitForTimeout(500);await page.reload();await tap('继续');s=await snap();assert.ok(s.buttons.find(b=>b.title==='继续').enabled,'Completion survives reload after actual playback');assert.ok(!s.state.flags.FOUND_FULL_RECORDING);await tap('继续');s=await snap();assert.ok(s.state.flags.FOUND_FULL_RECORDING);assert.equal(s.state.progress.nodeId,'CH08_EP03_DESK');assert.equal(s.audio.length,0,'Disposed AudioSource does not accumulate');assert.ok(!s.state.flags.UNDERSTOOD_BREAKUP_TRUTH);await page.screenshot({path:path.join(outDir,'returned-to-desk.png')});
assert.equal(errors.length,0);assert.equal(failedRequests.length,0);const report={result:'PASS',method:'Initial cursor fixture from genuine CH08 no-recording H5 save; actual touch play/pause/resume/media-ended/reload/complete; no running-state writes or seeks',playing,paused,still,completedSource:true,truthNotInvented:true,disposed:true,errors,failedRequests};fs.writeFileSync(path.join(outDir,'audio-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1});
