const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[url,outDir]=process.argv.slice(2);if(!outDir)throw Error('Usage: URL output-directory');
const sessionDiagnostics=process.argv.includes('--session-diagnostics'),sessionSamples=[];
const catalog=JSON.parse(fs.readFileSync('assets/resources/data/story/catalog.json')),nodes=new Map(catalog.chapters.flatMap(c=>JSON.parse(fs.readFileSync('assets/resources/'+c.resource+'.json')).episodes.flatMap(e=>JSON.parse(fs.readFileSync('assets/resources/'+e.resource+'.json')).nodes)).map(n=>[n.id,n]));
const base={CH01_EP02_C002:'B',CH02_EP06_CHOICE:'TELL',CH03_EP04_CHOICE:'DISCUSS',CH04_EP04_CHOICE:'ASK',CH05_EP05_CHOICE:'SHARE',CH07_EP04_CHOICE:'TOGETHER',CH09_EP01_CONTACT_CHOICE:'SEND',CH09_EP02_DISCLOSE_CHOICE:'TELL',CH09_EP04_MEETING_CHOICE:'MEET'};
const routes=[['REUNION',base,'FULL'],['GOODBYE',{...base,CH09_EP04_MEETING_CHOICE:'DECLINE'},'FULL'],['UNDERSTAND',{...base,CH09_EP01_CONTACT_CHOICE:'NONE'},'FULL'],['UNSENT',base,'FULL'],['TOGETHER',{...base,CH09_EP01_CONTACT_CHOICE:'NONE'},'NONE'],['IF_THEN',{...base,CH07_EP04_CHOICE:'PAUSE',CH09_EP01_CONTACT_CHOICE:'NONE'},'NONE']];
let browser;(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:540,height:960},hasTouch:true,isMobile:true});const page=await context.newPage(),errors=[],failedRequests=[],reports=[];fs.mkdirSync(outDir,{recursive:true});
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))failedRequests.push(r.url())});
const snap=()=>page.evaluate(()=>{const cc=window.cc,scene=cc?.director.getScene(),labels=[],buttons=[],scrolls=[];let state;function walk(n){if(!n.activeInHierarchy)return;const m=n.getComponent('StoryManager');if(m?.hasState())state=m.state;const l=n.getComponent(cc.Label);if(l)labels.push(l.string);const b=n.getComponent(cc.Button);if(b)buttons.push({title:n.children.find(c=>c.getComponent(cc.Label))?.getComponent(cc.Label)?.string,enabled:b.interactable,x:270+n.worldPosition.x/2,y:480-n.worldPosition.y/2});const sc=n.getComponent(cc.ScrollView);if(sc)scrolls.push({offset:sc.getScrollOffset().y,max:sc.getMaxScrollOffset().y});for(const c of n.children)walk(c)}if(scene)walk(scene);return{state,buttons,scrolls,labels,save:localStorage.getItem('yushengweiji.save.v1')}});
const tap=async title=>{for(let i=0;i<150;i++){const s=await snap(),b=s.buttons.find(b=>b.title===title&&b.enabled);if(b){await page.touchscreen.tap(b.x,b.y);await page.waitForTimeout(170);if(title==='继续'&&!s.state)await page.waitForFunction(()=>{const scene=window.cc?.director.getScene();return scene?.name==='Story'&&scene.children[0]?.getComponent('StoryManager')?.ready},{},{timeout:30000});return}await page.waitForTimeout(100)}const failed=await snap();fs.writeFileSync(path.join(outDir,'failure.json'),JSON.stringify({title,...failed,errors},null,2));await page.screenshot({path:path.join(outDir,'failure.png')});throw Error('No ready button '+title+' at '+failed.state?.progress.nodeId+' '+JSON.stringify(failed.labels))};
const cdp=await context.newCDPSession(page);
if(sessionDiagnostics)await cdp.send('Performance.enable');
async function sessionSample(round){
 await page.waitForTimeout(700);const before=await cdp.send('Performance.getMetrics');await cdp.send('HeapProfiler.collectGarbage');const after=await cdp.send('Performance.getMetrics'),dom=await cdp.send('Memory.getDOMCounters');
 const assets=await page.evaluate(async()=>{const cc=await System.import('cc');if(typeof cc.AudioSource!=='function')throw Error('Cocos AudioSource diagnostic export is unavailable');let cacheAssets=0,jsonAssets=0,textures=0,texturePixels=0,audioClips=0,storyManagers=0,audioSources=0;cc.assetManager.assets.forEach(a=>{cacheAssets++;if(a instanceof cc.JsonAsset)jsonAssets++;if(a instanceof cc.Texture2D){textures++;texturePixels+=a.width*a.height}if(a instanceof cc.AudioClip)audioClips++});function walk(n){if(n.getComponent('StoryManager'))storyManagers++;audioSources+=n.getComponents(cc.AudioSource).length;for(const c of n.children)walk(c)}walk(cc.director.getScene());return{cacheAssets,jsonAssets,textures,texturePixels,estimatedRGBABytes:texturePixels*4,audioClips,storyManagers,audioSources}});
 const heap=m=>m.metrics.find(x=>x.name==='JSHeapUsedSize').value;assert.equal(assets.storyManagers,0);assert.equal(assets.audioSources,0);return{round,heapBeforeDiagnosticGC:heap(before),heapAfterDiagnosticGC:heap(after),dom,...assets};
}
const swipe=async()=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:260,y:700}]});for(let y=650;y>=280;y-=45){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:260,y}]});await page.waitForTimeout(35)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200)};
const finishDocument=async title=>{for(let i=0;i<35;i++){const s=await snap();if(s.buttons.find(b=>b.title===title&&b.enabled))return;await swipe()}throw Error('Document did not reach final line')};
const tapInvestigationItem=async title=>{for(let i=0;i<3;i++){const s=await snap();if(s.buttons.some(b=>b.title===title&&b.enabled)){await tap(title);return}const pageControl=s.buttons.find(b=>b.enabled&&(b.title==='其余旧物'||b.title==='前面几件'));assert.ok(pageControl,'Investigation item is reachable '+title);await tap(pageControl.title);}throw Error('Unreachable investigation item '+title)};
await page.goto(url);await tap('继续');let oldEndings={};
for(let round=0;round<routes.length;round++){
 const[expected,options,evidence]=routes[round],visited=[],inspected=new Set();let last;
 for(let guard=0;guard<650;guard++){
  const s=await snap();assert.ok(s.state);assert.equal(s.state.playCount,round+1);assert.deepEqual(s.state.endings,oldEndings);const n=nodes.get(s.state.progress.nodeId);assert.ok(n);visited.push(n.id);
  if(n.type==='ending'){assert.equal(n.endingId,expected);assert.ok(!s.state.flags.ROUND_COMPLETED);await swipe();await page.screenshot({path:path.join(outDir,`${round+1}-${expected}.png`)});await tap('继续');last=await snap();assert.ok(last.state.flags.ROUND_COMPLETED);assert.ok(last.state.endings[expected]);break;}
  if(['passage','phone','narration','dialogue'].includes(n.type))await tap('继续');
  else if(n.type==='choice')await tap(n.options.find(o=>o.id===options[n.id]).text);
  else if(n.type==='investigation'){const item=n.items.find(i=>!inspected.has(n.id+':'+i.id)&&(!n.optional||evidence==='FULL'));if(item){inspected.add(n.id+':'+item.id);await tapInvestigationItem(item.text+(s.state.flags[item.viewedFlag]?'（看过）':''))}else await tap(n.doneText||'收好纸箱');}
  else if(n.type==='photo'){if(n.backText)await tap('翻面');await tap('放回去');}
  else if(n.type==='letter'){await tap(n.actionText||'查看');if(n.requireReadToEnd)await finishDocument('放回去');await tap('放回去');}
  else if(n.type==='audioInteraction'){await tap('查看录音文字');await finishDocument('继续');await tap('继续');}
  else if(n.type==='transition'){await page.waitForTimeout(550);await tap('继续');}
  else throw Error('Unexpected '+n.type);
 }
 assert.ok(last);oldEndings={...last.state.endings};const count=Object.values(oldEndings).filter(Boolean).length;assert.equal(count,round+1);assert.equal(last.state.life.time.year,2037);assert.equal(last.state.life.time.month,10);const saved=JSON.parse(last.save);assert.deepEqual(saved.endings,oldEndings);assert.deepEqual(saved.life.memoryRecords,last.state.life.memoryRecords);assert.deepEqual(saved.readNodeIds,last.state.readNodeIds);
 if(sessionDiagnostics){
  await tap('返回书桌');const raw=(await snap()).save;await tap('相册');
  const photos=require('../work/core/story/PhotoCatalog.js').albumPhotos.filter(p=>last.state.flags[p.flag]);
  for(let cycle=0;cycle<2;cycle++)for(const photo of photos){await tap(photo.title);await tap('翻面');await tap('返回相册');assert.equal((await snap()).save,raw,'Album never writes during a long session')}
  await tap('返回书桌');sessionSamples.push(await sessionSample(round+1));await tap('继续');
 }else{await page.reload();await tap('继续')}
 let restored=await snap();assert.ok(restored.labels.includes('这一页读完了。'));assert.deepEqual(restored.state.endings,oldEndings);assert.deepEqual(restored.state.flags,last.state.flags);assert.equal(restored.state.playCount,round+1);
 const report={round:round+1,ending:expected,evidence,steps:visited.length,visited,endState:last.state};reports.push(report);fs.writeFileSync(path.join(outDir,'rounds.json'),JSON.stringify({method:'All six rounds start at Boot/CH01 and use real touchscreen actions. Same local save retains completed endings; hidden ending occurs on round four after three distinct actual endings. No seeded or in-game state edits.',rounds:reports,errors,failedRequests},null,2));console.log('Round '+(round+1)+' '+expected+' PASS '+visited.length);
 await tap('再读一遍');for(let i=0;i<100;i++){restored=await snap();if(restored.state?.progress.chapterId==='CH01')break;await page.waitForTimeout(100)}assert.equal(restored.state.playCount,round+2);assert.deepEqual(restored.state.endings,oldEndings);assert.deepEqual(restored.state.flags,{});assert.deepEqual(restored.state.readNodeIds,[]);assert.deepEqual(restored.state.life.memoryRecords,{});assert.ok(Object.values(restored.state.stats).every(n=>n===0));
}
if(sessionDiagnostics){assert.equal(sessionSamples.length,6);fs.writeFileSync(path.join(outDir,'long-session.json'),JSON.stringify({result:errors.length||failedRequests.length?'FAIL':'PASS',method:'Six real rounds in one document without page reload, plus two full four-photo gallery cycles per round. JS heap before/after explicit diagnostic GC, public Cocos assets/textures/audio and DOM event counts observed. Estimated RGBA bytes are not GPU/RSS measurements or physical-device results.',samples:sessionSamples,errors,failedRequests},null,2)+'\n');assert.ok(sessionSamples.at(-1).cacheAssets<=sessionSamples[0].cacheAssets+8)}
assert.equal(errors.length,0);assert.equal(failedRequests.length,0);
fs.writeFileSync(path.join(outDir,'complete.json'),JSON.stringify({result:'PASS',distinctEndings:6,completedRounds:6,nextPlayCount:7,hiddenRound:4,metaRetained:true,currentFactsReset:true,sessionDiagnostics,errors,failedRequests},null,2));await browser.close();})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1});
