const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const resources=path.resolve(__dirname,'../assets/resources');
const catalog=JSON.parse(fs.readFileSync(path.join(resources,'data/story/catalog.json')));
const manifests=catalog.chapters.map(c=>JSON.parse(fs.readFileSync(path.join(resources,c.resource+'.json'))));
const nodes=new Map(manifests.flatMap(m=>m.episodes.flatMap(e=>JSON.parse(fs.readFileSync(path.join(resources,e.resource+'.json'))).nodes)).map(n=>[n.id,n]));
const out=path.resolve(process.argv[3] || path.join(__dirname,'../work/browser-report')),errors=[],requests=[],visited=[];fs.mkdirSync(out,{recursive:true});
const url=process.argv[2];if(!url)throw new Error('Usage: node tools/browser-smoke.cjs http://127.0.0.1:PORT [report-directory]');
const familyOption=process.env.CH02_FAMILY_CHOICE==='TELL'?'TELL':'WAIT';
const planOption=process.env.CH03_PLAN_CHOICE==='DISCUSS'?'DISCUSS':'ASSUME';
const summerOption=process.env.CH04_SUMMER_CHOICE==='ASK'?'ASK':'PROMISE',retriedChapters=[];
const jobOption=process.env.CH05_JOB_CHOICE==='SHARE'?'SHARE':'RETURN';
const careOption=process.env.CH07_CARE_CHOICE==='TOGETHER'?'TOGETHER':'PAUSE';
let activeBrowser;
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE ? {executablePath:process.env.BROWSER_EXECUTABLE} : {}),args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 activeBrowser=browser;
 const context=await browser.newContext({viewport:{width:540,height:960},hasTouch:true,isMobile:true});const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)requests.push({url:r.url(),status:r.status()})});page.on('requestfailed',r=>requests.push({url:r.url(),error:r.failure()?.errorText}));
 const snapshot=()=>page.evaluate(()=>{const cc=window.cc,scene=cc?.director.getScene();let manager;const labels=[],buttons=[],scrolls=[];function walk(n){if(!n.activeInHierarchy)return;const m=n.getComponent('StoryManager');if(m?.hasState())manager=m;const label=n.getComponent(cc.Label);if(label)labels.push(label.string);const b=n.getComponent(cc.Button);if(b){const t=n.children.find(c=>c.getComponent(cc.Label))?.getComponent(cc.Label)?.string;buttons.push({title:t,x:270+n.worldPosition.x/2,y:480-n.worldPosition.y/2,enabled:b.interactable})}const scroll=n.getComponent(cc.ScrollView);if(scroll)scrolls.push({offset:scroll.getScrollOffset().y,max:scroll.getMaxScrollOffset().y});for(const c of n.children)walk(c)}if(scene)walk(scene);return{scene:scene?.name,labels,buttons,scrolls,state:manager?.state,save:localStorage.getItem('yushengweiji.save.v1'),title:document.title}});
 const tap=async title=>{await page.waitForFunction(title=>{const cc=window.cc,scene=cc?.director.getScene();if(!scene)return false;let ready=false;function walk(n){if(!n.activeInHierarchy)return;const b=n.getComponent(cc.Button);if(b?.interactable&&n.children.some(c=>c.getComponent(cc.Label)?.string===title))ready=true;for(const c of n.children)walk(c)}walk(scene);return ready},title,{timeout:15000});let s=await snapshot();let b=s.buttons.find(b=>b.title===title&&b.enabled);assert.ok(b,'Missing active button '+title+' at '+s.state?.progress.nodeId);await page.touchscreen.tap(b.x,b.y);await page.waitForTimeout(400)};
 const menuReady=()=>page.waitForFunction(()=>{const cc=window.cc,scene=cc?.director.getScene();if(scene?.name!=='Main')return false;let ready=false;function walk(n){if(!n.activeInHierarchy)return;const button=n.getComponent(cc.Button);if(button?.interactable&&n.children.some(c=>c.getComponent(cc.Label)?.string==='继续'))ready=true;for(const c of n.children)walk(c)}walk(scene);return ready},{},{timeout:30000});
 const storyReady=()=>page.waitForFunction(()=>{const cc=window.cc,scene=cc?.director.getScene();if(scene?.name!=='Story'||!scene.children[0]?.getComponent('StoryManager')?.hasState())return false;let ready=false;function walk(n){if(!n.activeInHierarchy)return;if(n.getComponent(cc.Button)?.interactable||n.getComponent(cc.Label)?.string==='当前内容读完了。')ready=true;for(const c of n.children)walk(c)}walk(scene);return ready},{},{timeout:30000});
 const reload=async()=>{let before=(await snapshot()).state;await page.reload();await menuReady();await tap('继续');await storyReady();const after=(await snapshot()).state;assert.equal(after.progress.nodeId,before.progress.nodeId);assert.deepEqual(after.flags,before.flags);assert.deepEqual(after.stats,before.stats);assert.deepEqual(after.readNodeIds,before.readNodeIds,'Read history survives H5 reload');assert.deepEqual(after.life.memoryRecords,before.life.memoryRecords,'Evidence survives H5 reload');return after};
 await page.goto(url);await menuReady();await page.screenshot({path:path.join(out,'chapter01-menu.png')});await tap('继续');await storyReady();await page.waitForTimeout(800);
 let first=await snapshot();assert.ok(first.scrolls[0].max>0);const cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:260,y:680}]});
 for(let y=650;y>=590;y-=20){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:260,y}]});await page.waitForTimeout(80)}
 await page.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(1300);
 const scrolled=await snapshot();assert.ok(scrolled.state.progress.readingOffset>0.1,'Drag must scroll and persist');const offset=scrolled.state.progress.readingOffset;
 await reload();const restored=await snapshot();assert.ok(Math.abs(restored.state.progress.readingOffset-offset)<0.03,'Reading offset state restored');assert.ok(Math.abs(restored.scrolls[0].offset/restored.scrolls[0].max-offset)<0.03,'Reading offset UI restored');
 await page.screenshot({path:path.join(out,'chapter01-reading.png')});
 const inspected=new Set(),resumed=new Set(['passage']);
 for(let guard=0;guard<nodes.size*4;guard++){
  let s=await snapshot();if(s.labels.includes('当前内容读完了。'))break;
  const n=nodes.get(s.state?.progress.nodeId);assert.ok(n,'Unknown displayed node');visited.push(n.id);
  if(!resumed.has(n.type)||['CH02_EP01_N001','CH02_EP02_GYM','CH02_EP03_N001','CH02_EP06_HOME_HIDDEN','CH02_EP06_HOME_TOLD','CH03_EP01_N001','CH03_EP04_CHOICE','CH03_EP05_PHOTO','CH03_EP06_ENVELOPE','CH03_EP06_DISCUSS','CH03_EP06_ASSUME','CH04_EP01_N001','CH04_EP02_PAPER','CH04_EP03_KNOWN','CH04_EP03_LATE','CH04_EP04_CHOICE','CH04_EP05_PHOTO','CH04_EP06_ASK_AGAIN','CH04_EP06_PROMISE_AGAIN','CH05_EP01_N001','CH05_EP01_COST_NOTE','CH05_EP04_JOB_NOTE','CH05_EP05_CHOICE','CH05_EP06_SEPARATE','CH05_EP06_CORRECT','CH05_EP06_NOTE','CH06_EP01_N001','CH06_EP01_PAPER','CH06_EP03_SHIFT_NOTE','CH06_EP05_TALK','CH06_EP05_NOTE','CH06_EP06_N001','CH07_EP01_N001','CH07_EP04_CHOICE','CH07_EP05_NOTE','CH07_EP06_NOTE','CH07_EP07_N001','CH07_EP08_PHOTO','CH07_EP08_CLOSE'].includes(n.id)){await reload();resumed.add(n.type);s=await snapshot()}
  if(n.id==='CH02_EP03_N001'){assert.ok(s.labels.includes('那年暑假 · 残缺'));assert.equal(s.state.life.time.month,7);await page.screenshot({path:path.join(out,'chapter02-summer.png')})}
  if(['CH01_EP04_WINDOW','CH02_EP06_CLOSE','CH03_EP06_PHONE','CH04_EP06_CLOSE','CH05_EP06_CLOSE','CH06_EP06_DECEMBER'].includes(n.id)){
   const nextChapter=n.id==='CH01_EP04_WINDOW'?'CH02':n.id==='CH02_EP06_CLOSE'?'CH03':n.id==='CH03_EP06_PHONE'?'CH04':n.id==='CH04_EP06_CLOSE'?'CH05':n.id==='CH05_EP06_CLOSE'?'CH06':'CH07';const resource=manifests.find(m=>m.chapterId===nextChapter).episodes[0].resource;
   await page.evaluate(resource=>{const m=window.cc.director.getScene().children[0].getComponent('StoryManager');const failed=Promise.reject(new Error('章节读取失败测试'));failed.catch(()=>{});m.pending.set(resource,failed)},resource);
   await tap('继续');await page.waitForFunction(()=>{const cc=window.cc,scene=cc?.director.getScene();let shown=false;function walk(n){if(!n.activeInHierarchy)return;if(n.getComponent(cc.Label)?.string==='章节读取失败测试')shown=true;for(const c of n.children)walk(c)}if(scene)walk(scene);return shown},{},{timeout:30000});const failed=await snapshot();assert.ok(failed.labels.includes('章节读取失败测试'));assert.ok(!failed.labels.includes('当前内容读完了。'));assert.equal(failed.state.progress.chapterId,s.state.progress.chapterId);assert.equal(failed.state.progress.episodeId,s.state.progress.episodeId);assert.equal(JSON.parse(failed.save).progress.chapterId,s.state.progress.chapterId);
   await page.evaluate(resource=>window.cc.director.getScene().children[0].getComponent('StoryManager').pending.delete(resource),resource);
   await tap('重试');await page.waitForFunction(next=>window.cc?.director.getScene()?.children[0]?.getComponent('StoryManager')?.state.progress.chapterId===next,nextChapter,{timeout:30000});assert.equal((await snapshot()).state.progress.chapterId,nextChapter);retriedChapters.push(nextChapter);
  }else if(n.type==='passage'||n.type==='phone')await tap('继续');
  else if(n.type==='investigation'){
   const item=n.items.find(i=>!inspected.has(i.id));if(item){inspected.add(item.id);await tap(item.text+(s.state.flags[item.viewedFlag]?'（看过）':''))}else await tap('收好纸箱');
  }else if(n.type==='photo'){if(n.backText)await tap('翻面');if(['CH03_EP05_PHOTO','CH04_EP05_PHOTO','CH07_EP08_PHOTO'].includes(n.id))await page.screenshot({path:path.join(out,n.id+'-back.png')});await tap('放回去')}
  else if(n.type==='letter'){await tap(n.actionText??'查看');assert.ok((await snapshot()).labels.includes(n.text),'Opened paper matches JSON '+n.id);if(['CH03_EP06_ENVELOPE','CH04_EP02_PAPER','CH05_EP01_COST_NOTE','CH05_EP04_JOB_NOTE','CH05_EP06_NOTE','CH06_EP01_PAPER','CH06_EP03_SHIFT_NOTE','CH06_EP05_NOTE','CH07_EP01_NOTE','CH07_EP05_NOTE','CH07_EP06_NOTE'].includes(n.id))await page.screenshot({path:path.join(out,n.id+'-opened.png')});await tap('放回去')}
  else if(n.type==='choice'){await page.screenshot({path:path.join(out,n.id+'-decision.png')});await tap((n.id==='CH02_EP06_CHOICE'?n.options.find(o=>o.id===familyOption):n.id==='CH03_EP04_CHOICE'?n.options.find(o=>o.id===planOption):n.id==='CH04_EP04_CHOICE'?n.options.find(o=>o.id===summerOption):n.id==='CH05_EP05_CHOICE'?n.options.find(o=>o.id===jobOption):n.id==='CH07_EP04_CHOICE'?n.options.find(o=>o.id===careOption):n.options[1]).text)}
  else if(n.type==='audioInteraction'){await tap('播放');assert.ok((await snapshot()).labels.includes('录音暂时无法播放。可以读文字继续。'));await tap('继续')}
  else if(n.type==='transition'){await page.waitForTimeout(600);await tap('继续')}
  else throw new Error('Unexpected '+n.type);
  if(n.id==='CH01_EP04_BUS')await page.screenshot({path:path.join(out,'chapter01-bus.png')});
 }
 let end=await snapshot();const last=manifests.at(-1);assert.equal(end.state.progress.chapterId,last.chapterId);assert.equal(end.state.progress.episodeId,last.episodes.at(-1).id);assert.ok(visited.includes('CH02_EP02_GYM'));assert.ok(visited.includes('CH02_EP02_PHOTO'));assert.ok(visited.includes('CH02_EP05_MESSAGES'));const told=familyOption==='TELL';assert.ok(visited.includes(told?'CH02_EP06_HOME_TOLD':'CH02_EP06_HOME_HIDDEN'));assert.ok(!visited.includes(told?'CH02_EP06_HOME_HIDDEN':'CH02_EP06_HOME_TOLD'));assert.ok(end.state.flags[told?'CH02_TOLD_FAMILY_RELATION':'CH02_HID_FAMILY_RELATION']);assert.ok(end.labels.includes('当前内容读完了。'));assert.equal(end.state.life.time.year,2037);assert.equal(end.state.life.time.month,9);assert.equal(end.state.life.stage,'middleAge');assert.equal(end.state.life.time.timeline,'present');assert.ok(end.state.flags.TOLD_PARTNER_XIA);assert.ok(visited.includes('CH01_EP03_N006A'));assert.ok(!visited.includes('CH01_EP03_N006B'));
 for(const [a,b] of [['CH03_EP02_KNOWN','CH03_EP02_FIRST_NAME'],['CH03_EP04_FAMILY_KNOWN','CH03_EP04_FAMILY_LATE'],['CH03_EP06_FAMILY_KNOWN','CH03_EP06_FAMILY_LATE']]){assert.ok(visited.includes(told?a:b));assert.ok(!visited.includes(told?b:a))}
 assert.ok(visited.includes(planOption==='DISCUSS'?'CH03_EP06_DISCUSS':'CH03_EP06_ASSUME'));assert.ok(!visited.includes(planOption==='DISCUSS'?'CH03_EP06_ASSUME':'CH03_EP06_DISCUSS'));assert.ok(end.state.flags.CH03_SEEN_GRADUATION_PHOTO&&end.state.flags.CH03_SEEN_FUTURE_ENVELOPE);assert.ok(!end.state.flags.READ_FULL_LETTER);assert.equal(end.state.life.memoryRecords.GRADUATION.status,'fragmentary');
 const discuss=planOption==='DISCUSS',ask=summerOption==='ASK';for(const [yes,no,condition] of [['CH04_EP01_ASK','CH04_EP01_SET',discuss],['CH04_EP02_COMPARE','CH04_EP02_REARRANGE',discuss],['CH04_EP03_KNOWN','CH04_EP03_LATE',told],['CH04_EP05_AGREED','CH04_EP05_CORRECTED',ask],['CH04_EP06_LISTEN','CH04_EP06_FIX',discuss],['CH04_EP06_ASK_AGAIN','CH04_EP06_PROMISE_AGAIN',ask]]){assert.ok(visited.includes(condition?yes:no));assert.ok(!visited.includes(condition?no:yes));}assert.ok(end.state.flags[ask?'CH04_ASKED_SUMMER_PLAN':'CH04_PROMISED_FOR_XIA']);assert.ok(end.state.flags.CH04_READ_TIMETABLES&&end.state.flags.CH04_SEEN_STREET_PHOTO);assert.equal(end.state.life.memoryRecords.DISTANCE.status,'fragmentary');assert.equal(end.state.life.relationships.XIA,'已经分开');assert.ok(!end.state.flags.FOUND_FULL_RECORDING&&!end.state.flags.UNDERSTOOD_BREAKUP_TRUTH);assert.deepEqual(retriedChapters,['CH02','CH03','CH04','CH05','CH06','CH07']);
 const share=jobOption==='SHARE';for(const [yes,no,condition] of [['CH05_EP01_CHECK_FIRST','CH05_EP01_REMEMBER',ask],['CH05_EP02_FAMILY_KNOWN','CH05_EP02_FAMILY_LATE',told],['CH05_EP03_ASK_ROOM','CH05_EP03_SUGGEST_ROOM',discuss],['CH05_EP04_COMPARE','CH05_EP04_RECHECK',ask],['CH05_EP05_SHARE','CH05_EP05_RETURN',share],['CH05_EP06_SEPARATE','CH05_EP06_CORRECT',share]]){assert.ok(visited.includes(condition?yes:no));assert.ok(!visited.includes(condition?no:yes));}assert.ok(end.state.flags[share?'CH05_TALKED_JOB_CONDITIONS':'CH05_ASSUMED_RETURN_FOR_JOB']);assert.ok(end.state.flags.CH05_READ_PRACTICE_COSTS&&end.state.flags.CH05_READ_JOB_CONDITIONS&&end.state.flags.CH05_READ_START_DATES);assert.equal(end.state.life.memoryRecords.WORK_PLANS.status,'fragmentary');for(const [yes,no,condition] of [['CH06_EP01_SHARE','CH06_EP01_CORRECT',share],['CH06_EP02_EARLY','CH06_EP02_LATE',told],['CH06_EP03_ASKED','CH06_EP03_REVISED',ask],['CH06_EP03_LISTEN','CH06_EP03_RECONSIDER',discuss],['CH06_EP04_SEPARATE','CH06_EP04_CORRECTED',share]]){assert.ok(visited.includes(condition?yes:no));assert.ok(!visited.includes(condition?no:yes));}assert.ok(end.state.flags.CH06_READ_WORK_NOTE&&end.state.flags.CH06_READ_VISIT_DATES&&end.state.flags.CH06_READ_STATION_NOTE&&end.state.flags.CH06_PARTED_2013);assert.equal(end.state.life.memoryRecords.WORK_START.status,'fragmentary');assert.equal(end.state.life.memoryRecords.BREAKUP.status,'fragmentary');assert.deepEqual(end.state.endings,{});
 const together=careOption==='TOGETHER';for(const [yes,no,c]of [['CH07_EP01_EARLY','CH07_EP01_LATE',told],['CH07_EP01_LIST','CH07_EP01_RECHECK',share],['CH07_EP03_ASK','CH07_EP03_STOP',discuss],['CH07_EP04_CONFIRM','CH07_EP04_REVISE',ask],['CH07_EP04_TOGETHER','CH07_EP04_PAUSE',together],['CH07_EP06_SHARED','CH07_EP06_CHANGED',together],['CH07_EP07_DIVIDE','CH07_EP07_REVISE',together]]){assert.ok(visited.includes(c?yes:no));assert.ok(!visited.includes(c?no:yes));}assert.ok(visited.includes('CH07_EP01_AFTER_STATION'));assert.ok(end.state.flags.CH07_MARRIED_2020&&end.state.flags.CH07_ZHOUMAN_BORN_2021&&end.state.flags.CH07_SEEN_FAMILY_PHOTO);
 const saved=JSON.parse(end.save);assert.deepEqual(saved.readNodeIds,end.state.readNodeIds);assert.deepEqual(saved.life.memoryRecords,end.state.life.memoryRecords);
 for(const id of new Set(visited))assert.ok(saved.readNodeIds.includes(id),'Saved reading history includes '+id);
 for(const memory of Object.values(saved.life.memoryRecords)){assert.ok(memory.evidence.length>0);assert.ok(memory.evidence.every(e=>typeof e==='string'),'Evidence is a string array')}
 assert.ok(saved.life.memoryRecords.FIRST_MEETING.evidence.includes('旧体育馆午休'));assert.ok(saved.life.memoryRecords.HOME_SUMMER.evidence.includes('工厂送钥匙'));
 await reload();assert.ok((await snapshot()).labels.includes('当前内容读完了。'));
 const damaged=structuredClone(saved);damaged.readNodeIds=[{},...saved.readNodeIds.slice(-2)];damaged.life.memoryRecords.FIRST_MEETING.evidence=[{}];const raw=JSON.stringify(damaged);
 // Seed after the old page's hide-save and before the new Boot loads.
 await page.addInitScript(raw=>localStorage.setItem('yushengweiji.save.v1',raw),raw);await page.reload();await menuReady();await tap('继续');await storyReady();
 const recovered=await snapshot(),backup=await page.evaluate(()=>localStorage.getItem('yushengweiji.save.v1.v2.collections.backup'));assert.equal(backup,raw);assert.equal(recovered.state.progress.nodeId,saved.progress.nodeId);assert.deepEqual(recovered.state.flags,saved.flags);assert.deepEqual(recovered.state.life.memoryRecords.FIRST_MEETING.evidence,[]);assert.deepEqual(recovered.state.readNodeIds,saved.readNodeIds.slice(-2));assert.ok(recovered.labels.includes('当前内容读完了。'));
 const report={viewport:'540x960 touch',title:end.title,familyOption,planOption,summerOption,jobOption,careOption,retriedChapters,visited,inspectionItems:inspected.size,readingOffset:offset,resumedTypes:[...resumed],endState:end.state,v2BackupVerified:true,errors,failedRequests:requests};fs.writeFileSync(path.join(out,'browser-smoke.json'),JSON.stringify(report,null,2));
 assert.equal(errors.length,0);assert.equal(requests.filter(r=>!r.url.endsWith('/favicon.ico')).length,0);
 console.log(JSON.stringify({result:'PASS',visitedNodes:visited.length,inspectionItems:inspected.size,readingOffset:offset,resumedTypes:[...resumed],errors,requests},null,2));await browser.close();
})().catch(async e=>{console.error(e);await activeBrowser?.close();process.exitCode=1});

