const fs=require('node:fs'),path=require('node:path');
const{loadStory,prose,characters,baseChoices,play}=require('./story-analysis-lib.cjs');
const out=path.resolve(process.argv[2]||'docs/baseline');fs.mkdirSync(out,{recursive:true});const story=loadStory();
const rows=story.chapters.flatMap(c=>c.episodes.map(e=>{const records=story.records.filter(r=>r.episode===e.id),nodes=records.map(r=>r.node);return{chapter:c.chapterId,chapterTitle:c.title,episode:e.id,title:e.name,nodes:nodes.length,allBranchCharacters:nodes.reduce((sum,n)=>sum+prose(n).reduce((s,p)=>s+characters(p),0),0),choiceNodes:nodes.filter(n=>n.type==='choice').length,interactionNodes:nodes.filter(n=>['investigation','photo','letter','audioInteraction'].includes(n.type)).length,timeLabels:Array.from(new Set(nodes.flatMap(n=>n.lifeContext?.time?[n.lifeContext.time.label]:[]))),places:Array.from(new Set(nodes.flatMap(n=>n.lifeContext?.time?[n.lifeContext.time.location]:[])))}}));
const profiles=[['REUNION',baseChoices,'FULL'],['GOODBYE',{...baseChoices,CH09_EP04_MEETING_CHOICE:'DECLINE'},'FULL'],['UNDERSTAND',{...baseChoices,CH09_EP01_CONTACT_CHOICE:'NONE'},'FULL'],['UNSENT',baseChoices,'FULL'],['TOGETHER',{...baseChoices,CH09_EP01_CONTACT_CHOICE:'NONE'},'NONE'],['IF_THEN',{...baseChoices,CH07_EP04_CHOICE:'PAUSE',CH09_EP01_CONTACT_CHOICE:'NONE'},'NONE']];
const routes=[];let state;const{createNextRound}=require('../work/core/story/EndingResolver.js');
for(const[ending,choices,evidence]of profiles){const result=play(story,choices,evidence,state);const unique=Array.from(new Set(result.visited));const episodes=rows.map(row=>{const ids=unique.filter(id=>story.nodes.get(id).episode===row.episode);const count=ids.reduce((s,id)=>s+prose(story.nodes.get(id).node).reduce((n,p)=>n+characters(p),0),0);return{episode:row.episode,characters:count,estimatedMinutes:[Number((count/500).toFixed(2)),Number((count/400).toFixed(2))],outsideTarget:count/500>8||count/400<3}});routes.push({ending,evidence,visited:result.visited,episodes,characters:episodes.reduce((s,e)=>s+e.characters,0),method:'Domain runtime actions, one count per unique visited node. Audio transcript counted as optional text, back text counted when presented. No human duration inferred.'});state=createNextRound(result.state)}
const sequences=[];
for(const route of routes){const found=route;let run=[];let scene='';function flush(){if(run.length>=4)sequences.push({profile:route.ending,scene,nodes:run.map(n=>n.id),characters:run.reduce((s,n)=>s+prose(n).reduce((z,p)=>z+characters(p),0),0),review:'Four or more text nodes without an explicit location change or interaction. Editorial clue only; continuous life narration may be intentional.'});run=[]}
 for(const id of found.visited){const n=story.nodes.get(id).node;const location=n.lifeContext?.time?.location||scene;if(['passage','phone','dialogue','narration'].includes(n.type)){if(location!==scene)flush();scene=location;run.push(n)}else flush()}flush();
}
const report={inputHash:story.inputHash,chapters:story.chapters.length,episodes:rows.length,nodes:story.records.length,method:'All-branch totals include mutually exclusive content and are not play time. Six sampled domain routes give separate 400-500 character/minute estimates, not measured human time. Repeated investigation visits are deduplicated; optional reading/audio cannot be inferred from this model.',rows,routes,sequences};
fs.writeFileSync(path.join(out,'story-stats.json'),JSON.stringify(report,null,2)+'\n');
const md=['# 阅读体验基线','',report.method,'','| 章节 | 片段 | 全分支字数 | 已核模拟路线字数范围 | 估算分钟范围 | 决定节点 | 互动节点 |','| --- | --- | ---: | ---: | ---: | ---: | ---: |'];
for(const row of rows){const sampled=routes.map(r=>r.episodes.find(e=>e.episode===row.episode));md.push(`| ${row.chapter} | ${row.episode} ${row.title} | ${row.allBranchCharacters} | ${Math.min(...sampled.map(e=>e.characters))}–${Math.max(...sampled.map(e=>e.characters))} | ${Math.min(...sampled.map(e=>e.estimatedMinutes[0]))}–${Math.max(...sampled.map(e=>e.estimatedMinutes[1]))} | ${row.choiceNodes} | ${row.interactionNodes} |`)}
md.push('','3～8分钟是每片段目标。低于目标只提示复核，不自动扩写；应先检查可合并的短段、实际互动、人物的具体事情和真人停留。连续文字序列只是审读线索，不能按节点数强塞选项。','',`输入剧情散列：${story.inputHash}`);
fs.writeFileSync(path.join(out,'STORY_EXPERIENCE.md'),md.join('\n')+'\n');console.log(`Story experience exported: ${rows.length} episodes, ${routes.length} sampled profiles`);
